version: 2
jobs:
  build:
    working_directory: ~
    machine: true
    steps:
      - checkout
      # hugo install
      - run: 
          command: 'go get -u -v github.com/spf13/hugo'
      # submodule init
      - run:
          command: 'git submodule init && git submodule update'
      # hugo build
      - run:
          command: 'hugo'
      - save_cache:
          key: cache-{{ epoch }}
          paths:
            - ~
  deploy:
    working_directory: ~
    machine: true
    steps:
      - restore_cache:
          key: cache
      - run:
          command: 'rm -rf docs/'
      - run:
          command: 'cp -r public docs'
      - run:
          command: 'git config --global user.email "push@circleci.com"'
      - run:
          command: 'git config --global user.name "CircleCI"'
      - run:
          command: 'git branch master && git checkout master'
      - run:
          command: 'git add -A && git commit -m "[AUTO]Hugo Built"'
      - run:
          command: 'git push -f origin master'
workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: dev
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: dev
